# Generated by Django 5.0.1 on 2024-02-04 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('features', models.TextField()),
                ('benefits', models.TextField()),
                ('usps', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PricingStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_analysis', models.DecimalField(decimal_places=2, max_digits=10)),
                ('market_research', models.TextField()),
                ('pricing_model', models.CharField(max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweets.product')),
            ],
        ),
        migrations.CreateModel(
            name='DistributionChannels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channels', models.TextField()),
                ('partnerships', models.TextField()),
                ('logistics_fulfillment', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweets.product')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerFeedbackIteration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_feedback', models.TextField()),
                ('market_monitoring', models.TextField()),
                ('continuous_improvement', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweets.product')),
            ],
        ),
        migrations.CreateModel(
            name='CompetitiveAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitors', models.TextField()),
                ('swot_analysis', models.JSONField()),
                ('unique_value_proposition', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweets.product')),
            ],
        ),
        migrations.CreateModel(
            name='PromotionalTactics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketing_mix', models.JSONField()),
                ('advertising_promotion', models.TextField()),
                ('sales_promotions', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweets.product')),
            ],
        ),
        migrations.CreateModel(
            name='TargetMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demographics', models.JSONField()),
                ('psychographics', models.JSONField()),
                ('segmentation', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweets.product')),
            ],
        ),
    ]
