# Generated by Django 5.0.1 on 2024-02-07 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0002_product_color_product_size_cart_cartitem'),
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerfeedbackiteration',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prod.product'),
        ),
        migrations.AlterField(
            model_name='promotionaltactics',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prod.product'),
        ),
        migrations.AlterField(
            model_name='pricingstrategy',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prod.product'),
        ),
        migrations.AlterField(
            model_name='targetmarket',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prod.product'),
        ),
        migrations.AlterField(
            model_name='distributionchannels',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prod.product'),
        ),
        migrations.AlterField(
            model_name='competitiveanalysis',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prod.product'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
