# Generated by Django 5.0.1 on 2024-02-10 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_alter_customerfeedbackiteration_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerfeedbackiteration',
            name='product',
        ),
        migrations.RemoveField(
            model_name='distributionchannels',
            name='product',
        ),
        migrations.RemoveField(
            model_name='pricingstrategy',
            name='product',
        ),
        migrations.RemoveField(
            model_name='promotionaltactics',
            name='product',
        ),
        migrations.RemoveField(
            model_name='targetmarket',
            name='product',
        ),
        migrations.DeleteModel(
            name='CompetitiveAnalysis',
        ),
        migrations.DeleteModel(
            name='CustomerFeedbackIteration',
        ),
        migrations.DeleteModel(
            name='DistributionChannels',
        ),
        migrations.DeleteModel(
            name='PricingStrategy',
        ),
        migrations.DeleteModel(
            name='PromotionalTactics',
        ),
        migrations.DeleteModel(
            name='TargetMarket',
        ),
    ]
